CREATE TABLE `ee_candidato` (
  `id` bigint NOT NULL UNIQUE AUTO_INCREMENT,
  `cpf` varchar(11) COLLATE utf8_unicode_ci NOT NULL,
  `nome` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `nome_social` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `data_nasc` date NOT NULL,
  `telefone` varchar(11) COLLATE utf8_unicode_ci NOT NULL,
  `estado_civil` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `linkedin` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `github` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `portfolio` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `raca` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `genero` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `sexo_bio` varchar(9) COLLATE utf8_unicode_ci NOT NULL,
  `sobre` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `idioma` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pretensao_salarial` decimal(5,2)  DEFAULT NULL,
  `pcd` enum('fisica','auditiva','visual','mental','multipla') DEFAULT NULL,
  `id_fa` bigint DEFAULT NULL,
  `id_experiencia` bigint DEFAULT NULL,
  `tipo_permissao` enum('empresa','candidato','administrador'),
  `id_endereco` bigint DEFAULT NULL,
  `email_usuario` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `senha` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `data_cadastro` datetime NOT NULL,
  PRIMARY KEY (`id`)
);